### ISSUE TITLE
New driver not updated

### ISSUE THREAD

**Issue by suvanbalu** [museHD/Vocab-List-Gen#9]
update.py gets the required zip file and extracts it but doesn't replace the old driver. So I updated with the new driver in #8 . So do check it !

**Comment by suvanbalu** [comment]
![image](https://user-images.githubusercontent.com/46626983/135978778-3cdbc997-d4fb-4294-8b85-270b48855f69.png)
But this error doesn't occur when manually the new drive is moved

**Comment by museHD** [comment]
Hi @suvanbalu, is it download the chromedriver.exe in the GITHUB Directory? Please see if the latest commit fixes this as I don't see this issue on my end.

**Comment by suvanbalu** [comment]
![image](https://user-images.githubusercontent.com/46626983/136021225-25942b63-30ac-4a0e-b893-2794cbaf22fb.png)

When I run update.py , the .exe file is unzipped but it is  out of the directory

![image](https://user-images.githubusercontent.com/46626983/136021413-5d76a5b5-ed85-44d8-9538-62ea0975b573.png)

**Comment by suvanbalu** [comment]
Yeah I resolved the issue . Changed my terminal path to the repository and it works fine !
